#!/bin/sh


#   luci-theme-rta
#   Copyright (C) 2019-2024 The Sirpdboy Team <herboy2008@gmail.com> 
# 
#   Have a bug? Please create an issue here on GitHub!
#       https://github.com/rtaserver/RTA-Theme-OpenWrt/issues
# 
# Licensed to the public under the Apache License 2.0
LANG=`uci get luci.main.lang`
WORDDATETMP="/var/dayword_rtaword_date.tmp"
LOCK="/var/lock/dayword_rtaword.lock"
WORDTMP="/var/dayword_rtaword_$LANG.tmp"
test_url() {
	url=$1
	status="$(/usr/bin/curl -I -o /dev/null -skL --connect-timeout 1 --retry 1 -w %{http_code} "$url")"
	case "$status" in
		204|\
		200)
			echo '1'
		;;
	esac
}

get_word() {
	rta='rta'
	[ -s "/etc/config/rtaconfig" ] &&rta='rtaconfig'
	dayword="$(uci -q get $rta.@basic[0].dayword || echo '0')"
	case "$dayword" in
	*)
		local gwordjson=`curl -s 'https://raw.githubusercontent.com/rtaserver/RTA-Theme-OpenWrt/main/Kata-kata_hari_ini.json'` 
		local gword=`echo $gwordjson | jsonfilter -qe '@.content'`
		local gfrom=`echo $gwordjson | jsonfilter -qe '@.source'`
		[ -n "${gfrom}" ] && gfrom=$(echo "    ---- $gfrom")|| gfrom=''
		[ -n "${gword}" ] && echo "$gword     $gfrom"
		;;
	esac
}

rtaword() {
	lock="$LOCK"
	exec 200>"$lock"
	if flock -n 200 >"/dev/null" 2>&1; then
		local localword="$(get_word)"
		if [ -n "$localword" ]; then
			echo "$localword" >$WORDTMP 
			date +%Y%m%d > $WORDDATETMP
		fi
		flock -u 200 >"/dev/null" 2>&1
	fi
	[ -s "$WORDTMP" ] && cat $WORDTMP || echo -ne "Acquisition failed ,Please Issues:github@rtaserver"
}
check_url() {
if [ -f "$WORDDATETMP" ]; then
		localtime=`cat $WORDDATETMP | grep $(date +%Y%m%d) `
		if [ $localtime ]; then
		    [ -s "$WORDTMP" ] && cat $WORDTMP && return
		fi
	fi
local checknet=`ping -c 1 -W 1 8.8.8.8 > /dev/null 2>&1 &&echo 1 || echo 2`
if [ "x$checknet" == "x1" ]; then 
	rtaword
else
    	echo -ne "No internet connection, no information."
fi
}
check_url