#!/bin/sh
chmod +x /etc/init.d/rtaconfig
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@rtaconfig[-1]
	add ucitrack rtaconfig
	set ucitrack.@rtaconfig[-1].init=rtaconfig
	commit ucitrack
EOF
sed -i 's/cbi.submit\"] = true/cbi.submit\"] = \"1\"/g' /usr/lib/lua/luci/dispatcher.lua
[ -f /www/luci-static/argon/css/cascade.css ] && sed -i 's,media .. \"\/b,resource .. \"\/b,g' /usr/lib/lua/luci/view/themes/argon/sysauth.htm
rm -f /tmp/luci-indexcache
exit 0